# Generated by Django 4.2.1 on 2023-05-22 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentlike',
            old_name='post',
            new_name='comment',
        ),
    ]
